### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by ganwell** [concretecloud/chirp#10]
- [x]  Check builds on distros
- [x] macOS build
- [x] Documentation: Getting started page and most important functions page
- [ ] Review all documentation with somebody
- [ ] Improve comments in code with somebody else
- [x] Change work in progress to: beta-release

**Comment by ganwell** [comment]
Reviews are not done, but I move them to 1.1. The "1.0" milestone is reached.
