### ISSUE TITLE
Quickcheck todo

### ISSUE THREAD

**Issue by ganwell** [concretecloud/chirp#35]
- [x] Check function visibility and other keywords to conform chirp
- [x] Change function names to confirm chirp
- [x] Assimilate!!!
- [x]  Document it completely so Sven has nothing to do
- [x] Run chickcheck test: use few simple example
- [x] Memcheck it
- [ ] Review by two persons? Show them this checklist.
